In [2]:
import pandas as pd
import numpy as np
import sys

In [3]:
data = pd.read_excel('last_year.xlsx')

In [4]:
# remove all rows with NaN

data = data.dropna(how='all')
list(data)

['Tracking Number',
 'Employee Type',
 'Supervisor Name',
 'Laboratory',
 'Building',
 'Room',
 'Phone',
 'Judge',
 'Presentation Type',
 'Luncheon?',
 'Categories',
 'Abstract Status',
 'Title']

In [5]:
# select relevent information only

data_select = data[['Tracking Number','Employee Type', 'Laboratory', 'Judge', 'Presentation Type']]
data_select = data_select.fillna('Non')
group = data_select['Presentation Type'].value_counts()
print(group)
data_select.head()

Non    71
A      67
P      61
O      55
Name: Presentation Type, dtype: int64

,Tracking Number,Employee Type,Laboratory,Judge,Presentation Type
2,SC010536EB,Post Doctoral Fellow,LCP,N,Non
3,SC009159DN,Post Doctoral Fellow,LMB,N,Non
4,SC009915DV,Post Doctoral Fellow,GBB,Y,Non
5,SC009816DU,Post Baccalaureate Fellow,LMB,N,Non
6,SC009024DM,Post Doctoral Fellow,LDB,N,Non

In [6]:
# select everyone who agreed to be a judge

data_judges = data_select.loc[data_select['Judge'] == 'Y']
data_judges = data_judges.fillna('Non')
data_judges = data_judges.sort_values(by='Presentation Type')
group = data_judges['Presentation Type'].value_counts()
print(group)
data_judges.head()

O      51
P      38
A      11
Non    10
Name: Presentation Type, dtype: int64

    Tracking Number           Employee Type Laboratory Judge Presentation Type
126      SC008457DG                   Other       ODIR     Y                 A
9        SC010590EB  Principal Investigator        KDB     Y                 A
17       SC009384DP  Principal Investigator        LBG     Y                 A
42       SC008862DK  Principal Investigator       LCBB     Y                 A
46       SC010653EC         Staff Scientist        MDB     Y                 A

In [7]:
# randomly select 16 oral presentations

orals = data_judges.loc[data_judges['Presentation Type'] == 'O'].sample(n=16)
posters = pd.concat([data_judges, orals]).drop_duplicates(keep=False)
print(len(orals))
orals.head()

16

    Tracking Number         Employee Type Laboratory Judge Presentation Type
161      SC008934DL       Research Fellow       LERB     Y                 O
223      SC008853DK  Post Doctoral Fellow       LMCB     Y                 O
220      SC008727DJ     IRTA pre-doctoral        LDB     Y                 O
157      SC008844DK  Post Doctoral Fellow       LERB     Y                 O
254      SC010302DZ     IRTA pre-doctoral       LMCB     Y                 O

In [8]:
# replace orals that werr not selected as orals to poster

print(len(posters))
posters = posters.replace('O', 'P')
p_posters = posters.loc[posters['Presentation Type'] == 'P']
non_posters = posters.loc[posters['Presentation Type'] != 'P']
print(len(p_posters), len(non_posters))

94
73 21

In [80]:
# sort by labs

labs_p = p_posters.sort_values(by='Laboratory')
n_poster = len(labs_p)
print('# of posters: ', n_poster, '\n')
print(labs_p.head(), '\n')

labs_p = p_posters['Laboratory'].value_counts()
print(labs_p)

# of posters:  73

    Tracking Number         Employee Type Laboratory Judge Presentation Type
191      SC008619DI  Post Doctoral Fellow         BC     Y                 P
186      SC009789DT  Post Doctoral Fellow         DB     Y                 P
204      SC008691DI       Clinical Fellow        DDB     Y                 P
169      SC009780DT       Clinical Fellow        DDB     Y                 P
179      SC009474DQ     IRTA pre-doctoral        DDB     Y                 P

DEOB     11
LBG       8
LMCB      8
LDB       8
LCDB      7
KDB       5
DDB       5
LCP       4
LBC       4
LMB       4
PECRB     2
MDB       2
DB        1
GBB       1
BC        1
MMB       1
LERB      1
Name: Laboratory, dtype: int64

In [82]:
day_1 = 0
for i in range(len(labs_p)):
    day_1 += labs_p[i]
    day_1 += labs_p[-i-1]
    if day_1 > int(n_poster/2):
        print(i, day_1, n_poster-day_1)
        break

3 39 34

In [15]:
labs_p=labs_p.assign(freq=labs_p.groupby('Laboratory')['Laboratory'].transform('count')).sort_values(by=['freq', 'Laboratory'], ascending=[False, True])
labs_p

,Tracking Number,Employee Type,Laboratory,Judge,Presentation Type,freq
222,SC008835DK,Post Baccalaureate Fellow,DEOB,Y,P,11
245,SC008556DH,Post Baccalaureate Fellow,DEOB,Y,P,11
159,SC010239DY,Post Doctoral Fellow,DEOB,Y,P,11
236,SC009951DV,Post Doctoral Fellow,DEOB,Y,P,11
153,SC010176DX,Post Baccalaureate Fellow,DEOB,Y,P,11
201,SC010095DW,Clinical Fellow,DEOB,Y,P,11
218,SC008772DJ,IRTA pre-doctoral,DEOB,Y,P,11
243,SC009240DO,Research Fellow,DEOB,Y,P,11
142,SC009546DR,IRTA pre-doctoral,DEOB,Y,P,11
226,SC010572EB,Post Doctoral Fellow,DEOB,Y,P,11
224,SC009123DN,Post Baccalaureate Fellow,DEOB,Y,P,11
192,SC008961DL,Post Doctoral Fellow,LBG,Y,P,8
199,SC010194DX,Post Doctoral Fellow,LBG,Y,P,8
189,SC009528DR,Post Doctoral Fellow,LBG,Y,P,8
241,SC008988DL,Post Doctoral Fellow,LBG,Y,P,8
175,SC009312DP,Post Doctoral Fellow,LBG,Y,P,8
219,SC009078DM,Post Doctoral Fellow,LBG,Y,P,8
181,SC008601DI,Post Baccalaureate Fellow,LBG,Y,P,8
238,SC008907DL,Post Doctoral Fellow,LBG,Y,P,8
229,SC010365DZ,Post Doctoral Fellow,LDB,Y,P,8
205,SC010131DX,Post Doctoral Fellow,LDB,Y,P,8
202,SC009672DS,Post Doctoral Fellow,LDB,Y,P,8
195,SC010005DW,Post Baccalaureate Fellow,LDB,Y,P,8
206,SC008745DJ,Post Baccalaureate Fellow,LDB,Y,P,8
150,SC010059DW,IRTA pre-doctoral,LDB,Y,P,8
176,SC009897DU,Post Doctoral Fellow,LDB,Y,P,8
164,SC009870DU,Post Doctoral Fellow,LDB,Y,P,8
162,SC008403DG,Post Doctoral Fellow,LMCB,Y,P,8
163,SC009357DP,Other,LMCB,Y,P,8
228,SC009987DV,Post Baccalaureate Fellow,LMCB,Y,P,8
...,...,...,...,...,...,...
169,SC009780DT,Clinical Fellow,DDB,Y,P,5
179,SC009474DQ,IRTA pre-doctoral,DDB,Y,P,5
190,SC010086DW,Clinical Fellow,DDB,Y,P,5
244,SC009906DV,Clinical Fellow,DDB,Y,P,5
249,SC010356DZ,IRTA pre-doctoral,KDB,Y,P,5
250,SC009177DN,Research Fellow,KDB,Y,P,5
188,SC010284DY,Post Doctoral Fellow,KDB,Y,P,5
235,SC010347DZ,Post Baccalaureate Fellow,KDB,Y,P,5
193,SC010104DX,Post Doctoral Fellow,KDB,Y,P,5
141,SC010140DX,Post Doctoral Fellow,LBC,Y,P,4
248,SC008430DG,Post Doctoral Fellow,LBC,Y,P,4
167,SC010500EB,Post Doctoral Fellow,LBC,Y,P,4
237,SC010293DY,Post Doctoral Fellow,LBC,Y,P,4
200,SC009294DO,Research Fellow,LCP,Y,P,4
221,SC009366DP,Post Doctoral Fellow,LCP,Y,P,4
230,SC009564DR,Post Doctoral Fellow,LCP,Y,P,4
158,SC010518EB,Post Doctoral Fellow,LCP,Y,P,4
145,SC009150DN,Research Fellow,LMB,Y,P,4
194,SC008709DJ,Post Doctoral Fellow,LMB,Y,P,4
185,SC009618DS,Post Doctoral Fellow,LMB,Y,P,4
149,SC008682DI,IRTA pre-doctoral,LMB,Y,P,4
203,SC009762DT,Post Baccalaureate Fellow,MDB,Y,P,2
207,SC009393DP,Post Doctoral Fellow,MDB,Y,P,2
246,SC008754DJ,Post Baccalaureate Fellow,PECRB,Y,P,2
213,SC008916DL,Post Doctoral Fellow,PECRB,Y,P,2
191,SC008619DI,Post Doctoral Fellow,BC,Y,P,1
186,SC009789DT,Post Doctoral Fellow,DB,Y,P,1
210,SC008412DG,Research Fellow,GBB,Y,P,1
211,SC008502DH,Post Doctoral Fellow,LERB,Y,P,1
214,SC008952DL,Post Doctoral Fellow,MMB,Y,P,1

In [117]:
labs_nonp = non_posters['Laboratory'].value_counts()
print(labs_nonp)

LMCB     5
LERB     3
KDB      2
LBG      2
LCBB     1
GBB      1
ODIR     1
DB       1
LBC      1
OTHER    1
LMB      1
CEB      1
MDB      1
Name: Laboratory, dtype: int64

In [4]:
names = (data['Name'].to_list())
employee_types = (data['Employee Type'].to_list())
supervisor_names = (data['Supervisor Name'].to_list())
laboratories = (data['Laboratory'].to_list())
buildings =  (data['Building'].to_list())
rooms = (data['Room'].to_list())
judges = (data['Judge'].to_list())
presentation_types = (data['Presentation Type'].to_list())
research_keywords = (data['Research Keyword'].to_list())

In [5]:
class Fellow():
	def __init__(self):
		self.name=''
		self.employee_type=''
		self.supervisor_name=''
		self.laboratory=''
		self.building=''
		self.room=''
		self.judge=''
		self.presentation_type=''
		self.research_keyword=''	

		self.judges=[]

In [6]:
people = []
volunteer_judges_list = []

oral_list = []
poster_list = []

In [7]:
for i in range(len(names)):
	person = Fellow()
	people.append(person)
	person.name=names[i]
	person.employee_type=employee_types[i]
	if 'Fellow' not in person.employee_type and person.employee_type != 'IRTA pre-doctoral':
		volunteer_judges_list.append(person)
	person.presentation_type=presentation_types[i]
	if person.presentation_type == 'O':
		oral_list.append(person)
	elif person.presentation_type == 'P':
		poster_list.append(person)

In [8]:
###
### Check volunteer_judges_list ###
for person in volunteer_judges_list:
	print(person.employee_type)
###

Staff Scientist
Staff Scientist
Other
Technician
Staff Scientist
Staff Scientist
Other

In [9]:
###
### Check oral_list and poster_list###
for person in oral_list:
        print(person.name)
for person in poster_list:
	print(person.name)
###

Person2
Person4
Person6
Person11
Person13
Person19
Person22
Person24
Person25
Person27
Person28
Person7
Person10
Person14
Person18
Person20
Person21